-- MySQL Script generated by MySQL Workbench
-- Wed Dec  4 15:27:07 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pokemon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pokemon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pokemon` DEFAULT CHARACTER SET utf8 ;
USE `Pokemon` ;

-- -----------------------------------------------------
-- Table `Pokemon`.`Pokemon_Games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pokemon`.`Pokemon_Games` (
  `GameNames` VARCHAR(45) NULL,
  `GameImage` VARCHAR(45) NULL,
  `GenNumber` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pokemon`.`Pokemon_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pokemon`.`Pokemon_Type` (
  `Types` VARCHAR(45) NULL,
  `Normal` VARCHAR(45) NULL,
  `Fire` VARCHAR(45) NULL,
  `Water` VARCHAR(45) NULL,
  `Electric` VARCHAR(45) NULL,
  `Grass` VARCHAR(45) NULL,
  `Ice` VARCHAR(45) NULL,
  `Fighting` VARCHAR(45) NULL,
  `Poison` VARCHAR(45) NULL,
  `Ground` VARCHAR(45) NULL,
  `Flying` VARCHAR(45) NULL,
  `Psychic` VARCHAR(45) NULL,
  `Bug` VARCHAR(45) NULL,
  `Rock` VARCHAR(45) NULL,
  `Ghost` VARCHAR(45) NULL,
  `Dragon` VARCHAR(45) NULL,
  `Dark` VARCHAR(45) NULL,
  `Steel` VARCHAR(45) NULL,
  `Fairy` VARCHAR(45) NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
